Partially add Facebook button
ntuoss/hackoss-ui pull request #16
Opened 2018-10-20 08:46 UTC by kableGit

2018-10-27 14:19 UTC, ZaynJarvis requested changes
FYI, you may check out some footer designs here.
https://www.orbitmedia.com/blog/website-footer-design-best-practices/

2018-10-27 14:19 UTC, ZaynJarvis commented on src/app/pages/home/footer/footer.component.html
> +        <button type = "button" class = "btn">
It will be better to use the font-awesome icon for Facebook, Instagram, Github, and stuff.

2018-10-27 14:29 UTC, ZaynJarvis commented on src/app/pages/home/footer/footer.component.html
> +        <button type = "button" class = "btn">
https://github.com/orgs/ntuoss/projects/1
Also, refer to the project page for more information.

2018-11-02 18:09 UTC, clarencecastillo requested changes
Good stuff! May need to add more content to the footer later. Please do the requested changes first so we can approve this request. Thanks!!

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.ts
> +  heart = faHeart;
I think there's no need to have these icons defined here if you've already imported them in pages.module.ts. I'm not sure which is the best practice for this yet, but at least having them in one place might be the better option. Consider removing these given as they are redundant.

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +
Please consider re-indenting this file with 2 spaces. You can easily do this from VS code's command palette by running `Reindent Lines`.

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +        <button type = "button" class = "btn" margin = 2.5em>
I think using the attribute `margin` doesn't achieve anything in this case. If you want spaces between the icon buttons, please consider using the class `ml-1` here which sets some `margin-left` value. More info regarding these utility classes [here](https://getbootstrap.com/docs/4.1/utilities/spacing/#notation).

```suggestion
        <button type="button" class="btn ml-1">
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +        <fa-icon [icon] = "heart" class = "hrt" ></fa-icon>
I would think having in-line styling would be perfect for one-off cases like this. Also note that you can just refer to the :heart: icon using the icon's styling prefix (`fas`) followed by the icon name. You can easily look for em' [here](https://fontawesome.com/icons/heart?style=solid).

```suggestion
        <fa-icon [icon]="['fas', 'heart']" style="color: red;"></fa-icon>   
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +        <a href= "https://twitter.com/ntuoss" target="_blank">
Nice touch with the `target="_blank"`! 👍

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +        <fa-icon [icon] = "twt" class = "tweet"></fa-icon>
Like with the previous button, you can make reference to the Twitter icon using Font Awesome's icon style prefix for it (`fab`) followed by the icon name. You can get both information from the [official docs](https://fontawesome.com/icons/twitter?style=brands).
```suggestion
        <fa-icon [icon]="['fab', 'twitter']"></fa-icon>
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +            <fa-icon [icon] = "fb"> </fa-icon>
Suggest to change the reference to the Facebook icon too as described above.
```suggestion
            <fa-icon [icon]="['fab', 'facebook-f']"></fa-icon>      
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +        <div class="divider">
Not very clear why we need this empty `divider` 🤔

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +<nav class=" navbar navbar-dark bg-dark mt-10 clearfix">
Suggest you wrap everything inside the `.navbar` component inside a `<div class="container">...</div>` first. This should allow Bootstrap's responsive sizing to kick in. With that, you should be able to remove the `clearfix` class along with the `m-auto navbar-expand` classes from the respective children.

Should also be safe to just use a `div` tag instead of `nav` and also to remove the `mt-10` class which doesn't achieve anything.
```suggestion
<div class="navbar navbar-dark bg-dark">
  <div class="container">
    ...
  </div>
</div>
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +    <div class="navbar-expand m-auto navbar-text">
Don't forget to remove `navbar-expand` and `m-auto` from here once you've done the changes above.
```suggestion
    <div class="navbar-text">
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.html
> +    <div class="navbar-expand m-auto navbar-text ">
Please remove `navbar-expand` and `m-auto` from this class once you've done the change above.

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.scss
> +.bg-dark {
If you want the background of the footer to be black, you should use the css property `background-color` instead and set it as `black` with the `!important` flag.
```suggestion
.bg-dark {
  backround-color: black !important;
}
```

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.scss
> +.hrt{
Can take out once you've moved this in-line.

2018-11-02 18:09 UTC, clarencecastillo commented on src/app/pages/home/footer/footer.component.scss
> +.divider{
Not sure what's the point of this one.

2018-11-03 14:46 UTC, clarencecastillo approved these changes

2018-11-03 14:47 UTC, merged